In [1]:
import numpy as np

In [2]:
A = np.arange(30.).reshape(2,3,5)

In [3]:
A

array([[[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.]],

       [[15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.],
        [25., 26., 27., 28., 29.]]])

In [4]:
B = np.arange(24.).reshape(3,4,2)
B

array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.]],

       [[ 8.,  9.],
        [10., 11.],
        [12., 13.],
        [14., 15.]],

       [[16., 17.],
        [18., 19.],
        [20., 21.],
        [22., 23.]]])

In [6]:
np.tensordot(A, B,axes = ([0,1],[2,0]))

array([[ 820.,  970., 1120., 1270.],
       [ 871., 1033., 1195., 1357.],
       [ 922., 1096., 1270., 1444.],
       [ 973., 1159., 1345., 1531.],
       [1024., 1222., 1420., 1618.]])